import { headers } from "next/headers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const allHeaders = headers();
  const user = JSON.parse(allHeaders.get("x-user"));
  return (
    <html lang="en">
      <body>
        <header>
          <h2>Header</h2>
          <p>Chào bạn: {user?.fullname}</p>
        </header>
        {children}
      </body>
    </html>
  );
}
